export enum ProductUnit {
  GRAM = 'g',
  KILOGRAM = 'Kg',
  TON = 'tấn',
  MILLIMETER = 'mm',
  METER = 'm',
  PIECE = 'Cái',
  SET = 'Bộ',
  CLUSTER = 'cụm',
  SHEET = 'tấm',
  THREAD = 'sợi',
  ROLL = 'Cuộn',
  SQUARE_METER = 'm2',
  LITER = 'lít',
  CUBIC_METER = 'm3',
  STICK = 'cây',
  BAR = 'thanh',
  DRUM = 'thùng',
  PILL = 'viên',
  BOTTLE = 'chai',
  CAN = 'can',
  PACK = 'ram',
  BOX = 'hộp',
  BAG = 'bao',
  PAIR = 'đôi',
}
