export enum EUnitProduct {
  GRAM = "g",
  KILOGRAM = "kg",
  TON = "tấn",
  MILLIMETER = "mm",
  METER = "m",
  PIECE = "cái",
  SET = "bộ",
  CLUSTER = "cụm",
  SHEET = "tấm",
  THREAD = "sợi",
  ROLL = "cuộn",
  SQUARE_METER = "m2",
  LITER = "lít",
  CUBIC_METER = "m3",
  STICK = "cây",
  BAR = "thanh",
  DRUM = "thùng",
  PILL = "viên",
  BOTTLE = "chai",
  CAN = "can",
  PACK = "ram",
  BOX = "hộp",
  BAG = "bao",
  PAIR = "đôi",
}
